runtime: python39
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app --timeout 120

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  FLASK_ENV: 'development'
  MODEL_NAME: 'nlptown/bert-base-multilingual-uncased-sentiment'
